### ISSUE TITLE
(possibly spurious) Unrecognized escape sequences.

### ISSUE THREAD

**Issue by nigelkersten** [puppetlabs-toy-chest/puppetlabs-cve20113872#24]
`warning: Unrecognised escape sequence '\.' in file /etc/puppetlabs/puppet/modules/cve20113872/manifests/init.pp at line 44`
`warning: Unrecognised escape sequence '\.' in file /etc/puppetlabs/puppet/modules/cve20113872/manifests/init.pp at line 46`
`warning: Unrecognised escape sequence '\.' in file /etc/puppetlabs/puppet/modules/cve20113872/manifests/init.pp at line 48`

`44   validate_re($agent_localcacert, "^/.*?\.pem$")`

`46   validate_re($agent_hostcrl, "^/.*?\.pem$")`

`48   validate_re($agent_pidfile, "^/.*?\.pid$")`

I seem to remember geting these a lot whenever I tried passing regexes through to functions in the past, and that they're generally spurious.

**Comment by jhelwig** [comment]
Should probably change the `\.` to `\\.` to get Puppet to stop warning.
