### ISSUE TITLE
Step 4 (?) should restore agents' server settings to the previous master name

### ISSUE THREAD

**Issue by nfagerlund** [puppetlabs-toy-chest/puppetlabs-cve20113872#36]
If a user is going to the trouble of "purifying" the master's original CN and alt names (by swapping out the CA and all certs), we should restore the original (and presumably preferred) server setting. 

Is the step 4 class a good place to do this? It looks like it, but I might be missing something. For safety, we'd want to do it AFTER installing the new CA cert (and still before HUPping the daemon).

**Comment by nfagerlund** [comment]
Although it occurs to me that this might interact badly with the step2 class if that's still included in the catalog at this point. Hmm.

**Comment by nigelkersten** [comment]
I think this is the right place to do it.

**Comment by jeffmccune** [comment]
Step 4 is the right place to do it.  Should I cram this in now?
