### ISSUE TITLE
Step 5 should (?) remove remediation includes from site.pp

### ISSUE THREAD

**Issue by nfagerlund** [puppetlabs-toy-chest/puppetlabs-cve20113872#37]
What do you think, do we mind if these classes stick around in site.pp after remediation?

**Comment by jeffmccune** [comment]
It's probably a good idea to do this in step 5.  We could just restore a copy from an original copy we save in step1.

**Comment by jeffmccune** [comment]
I'm working on this now.  My plan is to save a backup copy of site.pp the first time we modify it and restore it in step5.
