### ISSUE TITLE
We shouldn't be enforcing that the agent is running as puppet/pe-puppet

### ISSUE THREAD

**Issue by nigelkersten** [puppetlabs-toy-chest/puppetlabs-cve20113872#40]
https://github.com/puppetlabs/puppetlabs-cve20113872/blob/master/manifests/step2.pp#L30

We really just want to validate this isn't an empty string in my opinion.

We have people who run puppet directly as root.

**Comment by nigelkersten** [comment]
as well as the group in that manifest, step4 does the same thing.

https://github.com/puppetlabs/puppetlabs-cve20113872/blob/master/manifests/step4.pp#L37

**Comment by jeffmccune** [comment]
This has been fixed and merged in 62a9bbd.  Closing issue.
