### ISSUE TITLE
check for puppetmaster is too loose.

### ISSUE THREAD

**Issue by nigelkersten** [puppetlabs-toy-chest/puppetlabs-cve20113872#42]
https://github.com/puppetlabs/puppetlabs-cve20113872/blob/master/manifests/step4.pp#L80

`if ($fact_is_puppetmaster != 'true') {`

If someone has deleted the files that this fact relies upon, so the fact is empty, we'll end up applying this to the puppetmaster.

Do we have a tighter test we can apply?

**Comment by stahnma** [comment]
In the upgrader process, we look at Puppet.conf and look to see the if
the puppet-server/puppet-master package is installed.

The problem really comes in when you have a master that isn't acting
as one, but is only acting as an inventory service receiver.  The only
method we were able to come up with to determine this case was CA =
false on the inventory service host and CA = true on the master
actually running manifests.  This still sucks and might not work in
multi-master environments.

On Fri, Oct 21, 2011 at 9:38 AM, Nigel Kersten
reply@reply.github.com
wrote:
