### ISSUE TITLE
Provide a way to scan a certificate store for Subject Alt Names

### ISSUE THREAD

**Issue by nigelkersten** [puppetlabs-toy-chest/puppetlabs-cve20113872#49]
Many of our users will have a single CA where every certificate that has ever been issued exists on the filesystem.

We should provide them with a simple tool to scan this whole store for certificates with Subject Alt Names, as well as some descriptive text that outlines what this output means.

e.g.

```
./scan_certificates.rb
./scan_certificates.rb --ssldir=/path/to/custom/ssl/dir

The following certificates have Subject Alternative Names set.

Certificate Name:     mycertificatename
Subject Alt Names:  [ 'foo', 'bar', 'baz' ]
```

**Comment by jeffmccune** [comment]
I'm going to work on this this afternoon.

-Jeff
