### ISSUE TITLE
webrick scan_certs errors out on RHEL5

### ISSUE THREAD

**Issue by aaron-grewell** [puppetlabs-toy-chest/puppetlabs-cve20113872#74]
On a RHEL 5.6 x86_64 Puppetmaster the webrick scan_certs script fails with the following error:
# ./scan_certs

./scan_certs:99:in `display': undefined method`reduce' for #Hash:0x2b20c2fef340 (NoMethodError)
    from ./scan_certs:68:in `run'
    from ./scan_certs:130:in`main'
    from ./scan_certs:145
# puppet --version

2.6.9
# ruby --version

ruby 1.8.5 (2006-08-25) [x86_64-linux]

**Comment by jeffmccune** [comment]
Aaron,

I'll take a look at fixing this ASAP.  Thanks for reporting the issue.

-Jeff
